# dbt profiles for dfp_analytics project
# Set DBT_PROFILES_DIR to this directory or copy to ~/.dbt/profiles.yml
#
# Data Flow:
#   - "dev" target: Connects to Spark Thrift Server in Kind cluster
#   - "prod" target: Connects to production Spark Thrift Server
#   - "legacy_duckdb" target: Legacy DuckDB mode (deprecated)
#
# Iceberg tables are stored on LakeFS with Avro format for versioned data.
#
# To start Spark Thrift Server in Kind:
#   kubectl apply -k infra/k8s/kind/addons/spark-thrift/

dfp:
  target: dev
  outputs:
    # Local development via Spark Thrift Server in Kind
    # Requires: kubectl apply -k infra/k8s/kind/addons/spark-thrift/
    # Exposed at localhost:10000 via NodePort
    dev:
      type: spark
      method: thrift
      host: "{{ env_var('SPARK_THRIFT_HOST', 'localhost') }}"
      port: "{{ env_var('SPARK_THRIFT_PORT', 10000) | int }}"
      schema: dfp
      # Iceberg catalog (configured in Thrift Server startup)
      catalog: lakefs_catalog
      file_format: iceberg

    # Production Spark Thrift Server connection
    prod:
      type: spark
      method: thrift
      host: "{{ env_var('SPARK_THRIFT_HOST', 'spark-thrift.prod.internal') }}"
      port: "{{ env_var('SPARK_THRIFT_PORT', 10000) | int }}"
      schema: dfp
      catalog: lakefs_catalog
      file_format: iceberg

    # Legacy DuckDB target (deprecated, kept for migration)
    legacy_duckdb:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH', 'data/dbt_dev.duckdb') }}"
      extensions:
        - httpfs
      settings:
        s3_region: "us-east-1"
        s3_url_style: "path"
