name: dfp_analytics
version: '1.0'
profile: dfp
model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # LakeFS repository for versioned Iceberg tables
  lakefs_repo: "{{ env_var('LAKEFS_REPOSITORY', 'kronodroid') }}"
  lakefs_branch: "{{ env_var('LAKEFS_BRANCH', 'main') }}"
  # Iceberg catalog name (must match profiles.yml)
  iceberg_catalog: "lakefs_catalog"
  iceberg_database: "dfp"
  # MinIO bucket for raw Avro data (from dlt)
  raw_bucket: "{{ env_var('MINIO_BUCKET_NAME', 'dlt-data') }}"
  raw_dataset: "kronodroid_raw"

models:
  dfp_analytics:
    # Global configuration for all models
    +file_format: iceberg
    +incremental_strategy: merge
    staging:
      +materialized: view
      +tags: ["staging"]
      kronodroid:
        +schema: stg_kronodroid
    marts:
      +materialized: table
      +tags: ["mart"]
      kronodroid:
        +schema: kronodroid
        # Mart tables are Iceberg tables with Avro storage
        +file_format: iceberg
